export const FontsVariant = {
  BodoniMT:'bodoni-mt-regular',
  BodoniMTItalic:'bodoni-mt-italic',
  BodoniMTBold:'bodoni-mt-bold',
  BodoniMTBoldItalic:'bodoni-mt-bold-italic',
  BodoniMTBlack:'bodoni-mt-black',
  BodoniMTBlackItalic:'bodoni-mt-black-italic',
  BodoniMTCondensed:'bodoni-mt-condensed',
  BodoniMTCondensedItalic:'bodoni-mt-condensed-italic',

  FuturaLT:'FuturaLT',
  FuturaLTBold:'FuturaLT-Bold',
  FuturaLTBoldOblique:'BoldOblique',
  FuturaLT:'FuturaLT-Book',
  FuturaLTBookOblique:'FuturaLT-BookOblique',
  FutureLTCondensed:'FuturaLT-Condensed',
  FuturaLTCondensedBold:'FuturaLT-CondensedBold',
  FuturaLTCondensedBoldOblique:'FuturaLT-CondensedBoldOblique',
  FuturaLTCondensedExtraBold:'FuturaLT-CondensedExtraBold',
  FuturaLTCondensedLight:'FuturaLT-CondensedLight',
  FuturaLTCondensedLightObl:'FuturaLT-CondensedLightObl',
  FuturaLTCondensedOblique:'FuturaLT-CondensedOblique',
  FuturaLTCondensedRegular:'FuturaLT-CondensedRegular',
  FuturaLTCondensedRegularObl:'FuturaLT-CondensedRegularObl',
  FuturaLTCondensedUltraLight:'FuturaLT-CondensedUltraLight',
  FuturaLTCondensedUltraLightObl:'FuturaLT-CondensedUltraLightObl',


  MontserratBlack:'Montserrat-Black',
  MontserratBlackItalic:'Montserrat-BlackItalic',
  MontserratBold:'Montserrat-Bold',
  MontserratBoldItalic:'Montserrat-BoldItalic',
  MontserratExtraBold:'Montserrat-ExtraBold',
  MontserratExtraBoldItalic:'Montserrat-ExtraBoldItalic',
  MontserratExtraLight:'Montserrat-ExtraLight',
  MontserratExtraLightItalic:'Montserrat-ExtraLightItalic',
  MontserratItalic:'Montserrat-Italic',
  MontserratLight:'Montserrat-Light',
  MontserratThinItalic:'Montserrat-ThinItalic',
  MontserratThin:'Montserrat-Thin',
  MontserratSemiBoldItalic:'Montserrat-SemiBoldItalic',
  MontserratSemiBold:'Montserrat-SemiBold',
  MontserratRegular:'Montserrat-Regular',
  MontserratMediumItalic:'Montserrat-MediumItalic',
  MontserratMedium:'Montserrat-Medium',
  MontserratLightItalic:'Montserrat-LightItalic',

  Inter: 'Inter-Regular'
};
